# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af64de1f21fe873fcdef7f0360a4a7d1fd9498383ef4c1d95a8a274bf66218b8a2c4ca9bc8f74a043c371342256a149b0c6a2ee289cd06c46890f9cb9ef08087

test:
  secret_key_base: a38f960c430cc4db02067e85021db04828af125e3f97275c75d5f12bc6c0022d6597d09d773cc736d4b8d006ff7a101b59bdc506b7429a98cea0d7d001c32f20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
